name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    paths-ignore:
      # Do not automatically run when a gradle-related file is modified
      - '**gradle**'
      - '.editorconfig'
    branches: [ master ]
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: ./gradlew clean check --continue
